apiVersion: v1
kind: Service
metadata:
  name: hellow-world-svc
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: chaka-http
  selector:
    app: hello-world-app